apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: alameens07/small-ms-order-service
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: DATABASE_URL